site_name: WIS2 in a box training
site_description: "WIS2 in a box (wis2box) is a Free and Open Source (FOSS) Reference Implementation of a WMO WIS2 Node. The project provides a plug and play toolset to ingest, process, and publish weather/climate/water data using standards-based approaches in alignment with the WIS2 principles. wis2box also provides access to all data in the WIS2 network. wis2box is designed to have a low barrier to entry for data providers, providing enabling infrastructure and services for data discovery, access, and visualization."
site_author: World Meteorological Organization
copyright: "&copy; 2023 World Meteorological Organization"
site_url: https://amrabouelenin.github.io/wis2docs/
#repo_url: https://github.com/wmo-im/wis2box-training
#edit_uri: tree/main/documentation/docs

docs_dir: docs
site_dir: /tmp/html

nav:
    - Home: index.md
    - Practical sessions:
        - Connecting to WIS2 over MQTT: practical-sessions/connecting-to-wis2-over-mqtt.md
        - Accessing your student VM: practical-sessions/accessing-your-student-vm.md
        - Initializing wis2box: practical-sessions/initializing-wis2box.md
        - Configuring datasets in wis2box: practical-sessions/configuring-wis2box-datasets.md
        - Configuring station metadata: practical-sessions/configuring-station-metadata.md
        - Monitoring WIS2 notifications: practical-sessions/monitoring-wis2-notifications.md
        - Converting SYNOP data to BUFR from the command line: practical-sessions/converting-synop-data-to-bufr.md
        - Converting SYNOP data to BUFR using the wis2box-webapp: practical-sessions/converting-synop-data-to-bufr-form.md
        - Converting CSV data to BUFR: practical-sessions/converting-csv-data-to-bufr.md
        - Automating data ingestion: practical-sessions/automating-data-ingestion.md
        - Adding GTS-headers to WIS2 notifications: practical-sessions/adding-gts-headers-to-wis2-notifications.md
        - Setting up a recommended dataset with access control: practical-sessions/datasets-with-access-control.md
        - Downloading data from WIS2: practical-sessions/downloading-data-from-wis2.md
        - Discovering datasets from the WIS2 Global Discovery Catalogue: practical-sessions/discovering-datasets-from-wis2-gdc.md
        - Querying data using the wis2box API: practical-sessions/querying-data-using-the-wis2box-api.md
        #- Working with BUFR data: practical-sessions/bufr-command-line-tools.md
    - Cheatsheets:
        - Linux: cheatsheets/linux.md
        - Docker: cheatsheets/docker.md
        - WIS2 in a box: cheatsheets/wis2box.md
    - csv2bufr templates:
        - AWS hourly: csv2bufr-templates/aws-template.md
        - DAYCLI: csv2bufr-templates/daycli-template.md


strict: true

use_directory_urls: true

theme:
    name: material
    palette:
        scheme: default
    features:
        - navigation.indexes
        - content.code.copy
    favicon: https://public.wmo.int/sites/all/themes/wmo/favicon.ico
    logo: assets/img/wmo-logo.png

plugins:
    - search
    - table-reader
    - i18n:
        docs_structure: folder
        languages:
          - locale: en
            default: true
            name: English
            build: true
          - locale: ru
            name: Русский
            build: true
            nav_translations:
                Home: "Главная"
                Practical sessions: "Практические занятия"
                Connecting to WIS2 over MQTT: "Подключение к WIS2 через MQTT"
                Accessing your student VM: "Доступ к вашей виртуальной машине студента"
                Initializing wis2box: "Инициализация wis2box"
                Configuring datasets in wis2box: "Настройка наборов данных в wis2box"
                Configuring station metadata: "Настройка метаданных станции"
                Monitoring WIS2 notifications: "Мониторинг уведомлений WIS2"
                Converting SYNOP data to BUFR from the command line: "Конвертация данных SYNOP в BUFR через командную строку"
                Converting SYNOP data to BUFR using the wis2box-webapp: "Конвертация данных SYNOP в BUFR с помощью веб-приложения wis2box"
                Converting CSV data to BUFR: "Конвертация CSV в BUFR"
                Automating data ingestion: "Автоматизация загрузки данных"
                Adding GTS-headers to WIS2 notifications: "Добавление заголовков GTS в уведомления WIS2"
                Setting up a recommended dataset with access control: "Настройка рекомендуемого набора данных с контролем доступа"
                Downloading data from WIS2: "Загрузка данных из WIS2"
                Discovering datasets from the WIS2 Global Discovery Catalogue: "Поиск наборов данных в Глобальном каталоге WIS2"
                Querying data using the wis2box API: "Запрос данных с использованием API wis2box"
                Cheatsheets: "Шпаргалки"
                Linux: "Linux"
                Docker: "Docker"
                # WIS2 in a box: "WIS2 в коробке"
                csv2bufr templates: "Шаблоны csv2bufr"
                AWS hourly: "AWS почасовой"
                DAYCLI: "DAYCLI"
          - locale: es
            name: Español
            build: true
            nav_translations:
                Home: "Inicio"
                Practical sessions: "Sesiones prácticas"
                Connecting to WIS2 over MQTT: "Conectarse a WIS2 a través de MQTT"
                Accessing your student VM: "Acceder a tu máquina virtual de estudiante"
                Initializing wis2box: "Inicializando wis2box"
                Configuring datasets in wis2box: "Configurando conjuntos de datos en wis2box"
                Configuring station metadata: "Configurando metadatos de estación"
                Monitoring WIS2 notifications: "Monitoreo de notificaciones de WIS2"
                Converting SYNOP data to BUFR from the command line: "Convertir datos SYNOP a BUFR desde la línea de comandos"
                Converting SYNOP data to BUFR using the wis2box-webapp: "Convertir datos SYNOP a BUFR usando la aplicación web wis2box"
                Converting CSV data to BUFR: "Convertir datos CSV a BUFR"
                Automating data ingestion: "Automatizar la ingesta de datos"
                Adding GTS-headers to WIS2 notifications: "Añadir encabezados GTS a notificaciones de WIS2"
                Setting up a recommended dataset with access control: "Configurar un conjunto de datos recomendado con control de acceso"
                Downloading data from WIS2: "Descargar datos de WIS2"
                Discovering datasets from the WIS2 Global Discovery Catalogue: "Descubrir conjuntos de datos en el Catálogo Global de Descubrimiento de WIS2"
                Querying data using the wis2box API: "Consultar datos usando la API de wis2box"
                Cheatsheets: "Hojas de referencia"
                Linux: "Linux"
                Docker: "Docker"
                # WIS2 in a box: "WIS2 en una caja"
                csv2bufr templates: "Plantillas csv2bufr"
                AWS hourly: "AWS por hora"
                DAYCLI: "DAYCLI"
    - print-site

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - meta
    - pymdownx.details
    - pymdownx.superfences
    - tables

extra_css:
    - assets/css/custom.css